# -*- coding: utf-8 -*-
"""AdminMenu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oZmUBrtteddbAIErhL7F7r6rDVKCtILu
"""

def adminMenu():
    adminDashBoard()
def adminDashBoard():
        try :
            print("\n****************************\n*........DashBoard.........*\n*please choose the option :*\n*1.view courses            *\n*2.add Courses            *\n*3.Number of registered students           * \n*4.delete course  *\n*5.quit                    *\n****************************\n")
            print("Enter 5 to quit")
            option = int(input())
            if option==1 :
                adminCourses()
            elif option==2:
                addCourses()
            elif option==3:
                getNumberofRegisteredStudents()
            elif option==4:
                deleteCourse()
            elif option==0:
                adminMenu()
            elif option==5:
                Quit()
            else :
                print("please enter valid option")
                adminMenu()
        except :
            print("Please enter valid input")
            adminMenu()
def adminDepartment():
    try :
        print("Select the sector")
        departments = ["CSE/IT","ECE","EEE","MECH","CIVIL"]
        for i in range(len(departments)):
            print(i+1,":",departments[i])
        print("Enter 0 to go back")
        global dep
        dep = int(input())
        if(dep>=1 and dep<6):
            return dep
        elif(dep==0):
            adminDashBoard()
        else:
            print("please enter valid option")
            adminDepartment()
    except :
        print("Please enter valid input")
        adminDepartment()
def adminCourses():
    print("****************************************************************************")
    print("*....................Course Details........................................*")
    print("*.....I can help you to give course details here..select your sector.......*")
    print("*..........................................................................*")
    print("****************************************************************************")
    adminDepartment()
    print("...... your course details are......")
    department_courses()
def addCourses():
    adminDepartment()
    try :
        print("add a course")
        opt = input()

        all_courses[dep].append(opt)
        print("....congratualations....\nyou have succesfully update an extra course after updating the courses are ....")
        print(all_courses[dep])
    except:
        print("please enter a valid input")
        adminDashBoard()
def getNumberofRegisteredStudents():
    adminDepartment()
    list_of_registeredstudents = {1:{100:"Machine Learning",92:"Web Development",86:"Game Development",108:"Data Science"},
                                  2:{76:"VLSI",92:"IOT",82:"Optical Networks",94:"Embedded Systems"},
                                  3:{123:"Java Programming",97:"Power Systems",124:"Robotics",91:"IOT"},
                                  4:{85:"Engineering Mechanics",99:"Robotics",100:"Python Programming",80:'IOT'},
                                  5:{67:"Construction Management",142:"C++ Programming",86:"C Programming",95:"Java Programming"}
                                  }
    print("the registered students")
    reg_noof_students = list_of_registeredstudents[dep]
    for k,v in reg_noof_students.items():
            print(v,"-",k)
def deleteCourse():
    adminDepartment()
    print("Enter 0 to go back\nWhich course you want to delete: ")
    department_courses()
    try : 
        delete=int(input())
        del(all_courses[dep][delete])
        print("after the deletion the courses are ")
        print(all_courses[dep-1])
    except :
        print("please enter a valid input")
        adminDashBoard()
def department_courses():
    cse_courses=["Machine Learning","Web Development","Game Development","Data Science"]
    ece=["VLSI","IOT","Optical Networks","Embedded Systems"]
    eee=["Java Programming","Power Systems","Robotics","IOT"]
    mech=["Engineering Mechanics","Robotics","Python Programming",'IOT']
    civil=["Construction Management","C++ Programming","C Programming","Java Programming"]
    global all_courses
    all_courses=[cse_courses,ece,eee,mech,civil]
    count=1
    for k in all_courses[dep-1]:
        print("{}. {}".format(count,k))
        count+=1
def Quit():
    print("\nYou are successfully logged out")
    print("...................................")
    print("Thank You!!!")
adminMenu()
